// Generated by CoffeeScript 1.6.3
(function() {
  var fs, http, jade, node_static, send404, server, settings, staticServer, url;

  http = require("http");

  url = require("url");

  fs = require("fs");

  node_static = require("node-static");

  jade = require("jade");

  settings = require("./settings");

  staticServer = new node_static.Server("./public");

  server = http.createServer(function(req, res) {
    var path;
    path = url.parse(req.url).pathname;
    switch (path) {
      case "/":
        res.writeHead(200, {
          "Content-Type": "text/html"
        });
        res.write(jade.renderFile("views/index.jade"));
        return res.end();
      default:
        return staticServer.serve(req, res);
    }
  });

  send404 = function(res) {
    res.writeHead(404);
    res.write("404 Not found.");
    return res.end();
  };

  server.listen(settings.port);

  require("./socket").listen(server);

}).call(this);
